require("ali.plugins_setup")

require("ali.plugins.bufferline")
require("ali.plugins.dashboard")
require("ali.plugins.telescope")
require("ali.plugins.nvim_tree")
require("ali.plugins.treesitter")
require("ali.core.options")
require("ali.core.keymaps")
require("ali.core.colorscheme")
require("ali.core.live_update")
